
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-skiff.fullname" . }}
  labels:
    {{- include "k8s-skiff.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
