
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-skiff.fullname" . }}
  labels:
    {{- include "k8s-skiff.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
